definitions:
  Feedback:
    properties:
      body:
        type: string
        x-go-name: Body
      category:
        type: string
        x-go-name: Category
      createdAt:
        type: string
        x-go-name: CreatedAt
      id:
        format: int64
        type: integer
        x-go-name: Id
      status:
        type: string
        x-go-name: Status
      title:
        type: string
        x-go-name: Title
      updatedAt:
        type: string
        x-go-name: UpdatedAt
      userId:
        format: int64
        type: integer
        x-go-name: UserId
    type: object
    x-go-package: product-feedback/feedback
  User:
    properties:
      avatar_url:
        type: string
        x-go-name: AvatarUrl
      created_at:
        type: string
        x-go-name: CreatedAt
      email:
        type: string
        x-go-name: Email
      id:
        format: int64
        type: integer
        x-go-name: Id
      name:
        type: string
        x-go-name: Name
      updated_at:
        type: string
        x-go-name: UpdatedAt
      user_name:
        type: string
        x-go-name: UserName
    type: object
    x-go-package: product-feedback/user
info: {}
paths:
  /api/feedback:
    delete:
      description: Delete product feedback
      operationId: deleteFeedback
      responses:
        "200":
          $ref: '#/responses/okResponse'
        "404":
          $ref: '#/responses/notFoundResponse'
      tags:
      - feedback
    get:
      description: Returns all product feedback in the system
      operationId: getAllFeedback
      responses:
        "200":
          $ref: '#/responses/getAllFeedbackResponse'
      tags:
      - feedback
    post:
      description: Create product feedback
      operationId: createFeedback
      responses:
        "200":
          $ref: '#/responses/createFeedbackResponse'
      tags:
      - feedback
  /api/feedback/:id:
    get:
      description: Returns product feedback by id
      operationId: updateFeedback
      responses:
        "200":
          $ref: '#/responses/okResponse'
        "400":
          $ref: '#/responses/badRequestResponse'
        "404":
          $ref: '#/responses/notFoundResponse'
      tags:
      - feedback
  /api/users/:id:
    get:
      description: Returs user data by id
      operationId: getUserById
      responses:
        "200":
          $ref: '#/responses/getUserResponse'
        "404":
          $ref: '#/responses/errorResponse'
      tags:
      - users
  /api/users/me:
    get:
      description: Returs user data
      operationId: getMe
      responses:
        "200":
          $ref: '#/responses/getUserResponse'
      tags:
      - users
responses:
  badRequestResponse:
    description: Bad request response
    schema:
      properties:
        message:
          type: string
          x-go-name: Message
      type: object
  createFeedbackResponse:
    description: OK response
    schema:
      properties:
        feedbackId:
          description: id of a newly created feedback
          type: string
          x-go-name: FeedbacId
      type: object
  errorResponse:
    description: Error response
    schema:
      properties:
        message:
          type: string
          x-go-name: Message
      type: object
  getAllFeedbackResponse:
    description: Returns all product feedback in the system
    schema:
      items:
        $ref: '#/definitions/Feedback'
      type: array
  getFeedbackByIdResponse:
    description: Returns product feedback by id
    schema:
      $ref: '#/definitions/Feedback'
  getUserResponse:
    description: OK response
    schema:
      $ref: '#/definitions/User'
  notFoundResponse:
    description: Not found feedback response
    schema:
      properties:
        message:
          type: string
          x-go-name: Message
      type: object
  okResponse:
    description: OK response
    schema:
      properties:
        message:
          description: OK message
          type: string
          x-go-name: Message
      type: object
swagger: "2.0"
