name: CI

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Lint
        run: make lint

      - name: Test
        run: make test_coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

      - name: Build
        run: make build

      # Heroku is not free anylonger
      # - name: Deploy
      #   uses: akhileshns/heroku-deploy@v3.12.12
      #   with:
      #     heroku_api_key: ${{secrets.HEROKU_API_KEY}}
      #     heroku_app_name: go-product-feedback
      #     heroku_email: ${{secrets.HEROKU_EMAIL}}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Create .env file
        run: |
          echo "${{secrets.ENV_FILE}}" > .env

      - name: Build & push Docker image
        env:
          REGISTRY: ghcr.io
          OWNER: arthur199212
          IMAGE_NAME: product-feedback
          IMAGE_TAG: ${{github.sha}}
        run: |
          docker build \
              -t $REGISTRY/$OWNER/$IMAGE_NAME:$IMAGE_TAG -t $REGISTRY/$OWNER/$IMAGE_NAME:latest \
              --label "org.opencontainers.image.source=https://github.com/$OWNER/{{github.repository}}" \
              .
          docker push $REGISTRY/$OWNER/$IMAGE_NAME:latest
