name: CI

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Lint
        run: make lint

      - name: Test
        run: make test_coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

      - name: Build
        run: make build

      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: go-product-feedback
          heroku_email: ${{secrets.HEROKU_EMAIL}}
